FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt requirements-dashboard.txt pyproject.toml ./
COPY src ./src
RUN pip install --no-cache-dir -r requirements-dashboard.txt && pip install --no-cache-dir -e .

EXPOSE 8501

CMD ["streamlit", "run", "src/nba_predictor/dashboard/app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]

